const db = require("./_db");


const chapters = [
  // ── 여호수아 (Joshua) 24장 ──
  { book_id: "joshua", chapter: 1, summary: "여호수아의 소명 — 강하고 담대하라는 하나님의 명령" },
  { book_id: "joshua", chapter: 2, summary: "정탐꾼과 기생 라합 — 붉은 줄로 맺은 구원의 약속" },
  { book_id: "joshua", chapter: 3, summary: "요단강 도하 — 언약궤 앞에서 물이 끊어짐" },
  { book_id: "joshua", chapter: 4, summary: "12개 돌 기념비 — 요단강 건넌 것을 기념함" },
  { book_id: "joshua", chapter: 5, summary: "길갈 할례와 유월절 — 만나가 그침, 가나안 소산을 먹음" },
  { book_id: "joshua", chapter: 6, summary: "여리고 성 함락 — 7일간 돌고 성벽이 무너짐" },
  { book_id: "joshua", chapter: 7, summary: "아간의 범죄 — 아이 성 패배와 진노의 원인" },
  { book_id: "joshua", chapter: 8, summary: "아이 성 정복 — 매복 전략으로 승리, 에발 산 제단" },
  { book_id: "joshua", chapter: 9, summary: "기브온 사람들의 속임 — 낡은 옷과 마른 빵으로 조약 체결" },
  { book_id: "joshua", chapter: 10, summary: "태양이 멈춤 — 기브온 전투, 남방 5왕 처단" },
  { book_id: "joshua", chapter: 11, summary: "북방 연합군 격파 — 하솔 왕 야빈 정복" },
  { book_id: "joshua", chapter: 12, summary: "정복한 31왕의 목록 — 요단 동서편 왕들 나열" },
  { book_id: "joshua", chapter: 13, summary: "아직 정복하지 못한 땅 — 르우벤, 갓, 므낫세 반 지파 분배" },
  { book_id: "joshua", chapter: 14, summary: "갈렙의 헤브론 — 85세 갈렙이 믿음으로 산지를 요청" },
  { book_id: "joshua", chapter: 15, summary: "유다 지파의 기업 — 경계선과 성읍 목록" },
  { book_id: "joshua", chapter: 16, summary: "에브라임 지파의 기업 — 요셉 자손의 땅 분배" },
  { book_id: "joshua", chapter: 17, summary: "므낫세 반 지파 기업 — 삼림을 개간하라는 명령" },
  { book_id: "joshua", chapter: 18, summary: "실로에 회막 설치 — 나머지 7지파 땅 측량과 분배" },
  { book_id: "joshua", chapter: 19, summary: "시므온부터 단까지 6지파 기업 분배 완료" },
  { book_id: "joshua", chapter: 20, summary: "6개 도피성 지정 — 과실치사자의 피난처" },
  { book_id: "joshua", chapter: 21, summary: "레위인의 48개 성읍 — 각 지파에서 배정" },
  { book_id: "joshua", chapter: 22, summary: "요단 동편 제단 논쟁 — 르우벤, 갓, 므낫세의 증거 제단" },
  { book_id: "joshua", chapter: 23, summary: "여호수아의 고별 훈시 — 이방 민족과 섞이지 말라" },
  { book_id: "joshua", chapter: 24, summary: "세겜 언약 — 너희가 섬길 자를 택하라, 여호수아 죽음" },

  // ── 사사기 (Judges) 21장 ──
  { book_id: "judges", chapter: 1, summary: "가나안 정복 미완 — 유다의 승리, 일부 지파의 실패" },
  { book_id: "judges", chapter: 2, summary: "보김에서의 천사 경고 — 사사 시대 순환 패턴 소개" },
  { book_id: "judges", chapter: 3, summary: "옷니엘, 에훗, 삼갈 — 에훗이 모압 왕 에글론을 찌름" },
  { book_id: "judges", chapter: 4, summary: "드보라와 바락 — 야엘이 시스라의 관자놀이에 말뚝을 박음" },
  { book_id: "judges", chapter: 5, summary: "드보라의 승리의 노래 — 별들이 시스라와 싸웠도다" },
  { book_id: "judges", chapter: 6, summary: "기드온의 소명 — 미디안 압제, 양털 징표 두 번 시험" },
  { book_id: "judges", chapter: 7, summary: "기드온의 300용사 — 횃불과 나팔로 미디안 대군 격파" },
  { book_id: "judges", chapter: 8, summary: "기드온의 미디안 추격 — 세바와 살문나 처단, 금 에봇 제작" },
  { book_id: "judges", chapter: 9, summary: "아비멜렉의 참탈 — 70형제 살해, 요담의 우화, 비참한 죽음" },
  { book_id: "judges", chapter: 10, summary: "돌라와 야일 — 이스라엘의 우상숭배와 암몬 압제" },
  { book_id: "judges", chapter: 11, summary: "입다의 서원 — 암몬 격파 후 딸을 번제로 드림" },
  { book_id: "judges", chapter: 12, summary: "에브라임과의 내분 — 쉽볼렛 사건, 42,000명 죽음" },
  { book_id: "judges", chapter: 13, summary: "삼손 탄생 예고 — 마노아 부부에게 나타난 여호와의 사자" },
  { book_id: "judges", chapter: 14, summary: "삼손의 결혼 — 사자를 찢고, 수수께끼를 냄" },
  { book_id: "judges", chapter: 15, summary: "삼손의 복수 — 여우 300마리 불, 나귀 턱뼈로 1,000명 침" },
  { book_id: "judges", chapter: 16, summary: "삼손과 들릴라 — 머리카락의 비밀, 신전 무너뜨림" },
  { book_id: "judges", chapter: 17, summary: "미가의 신상 — 레위인을 개인 제사장으로 고용" },
  { book_id: "judges", chapter: 18, summary: "단 지파의 이주 — 미가의 신상과 제사장 탈취" },
  { book_id: "judges", chapter: 19, summary: "기브아의 만행 — 레위인의 첩이 참혹하게 죽음" },
  { book_id: "judges", chapter: 20, summary: "베냐민 전쟁 — 이스라엘 연합군의 기브아 응징" },
  { book_id: "judges", chapter: 21, summary: "베냐민 지파 보존 — 실로 처녀 탈취로 멸종 방지" },

  // ── 룻기 (Ruth) 4장 ──
  { book_id: "ruth", chapter: 1, summary: "나오미와 룻 — 어머니의 하나님이 내 하나님이니이다" },
  { book_id: "ruth", chapter: 2, summary: "보아스의 밭에서 이삭 줍기 — 룻에 대한 은혜와 배려" },
  { book_id: "ruth", chapter: 3, summary: "타작마당의 밤 — 룻이 보아스에게 기업 무를 자의 책임 요청" },
  { book_id: "ruth", chapter: 4, summary: "보아스와 룻의 결혼 — 오벳 탄생, 다윗의 조상 족보" },

  // ── 사무엘상 (1 Samuel) 31장 ──
  { book_id: "1samuel", chapter: 1, summary: "한나의 기도 — 실로에서 눈물로 아들을 서원하고 사무엘 탄생" },
  { book_id: "1samuel", chapter: 2, summary: "한나의 찬송과 엘리 아들들의 악행 — 사무엘의 성장" },
  { book_id: "1samuel", chapter: 3, summary: "사무엘의 소명 — 밤에 세 번 부르신 하나님의 음성" },
  { book_id: "1samuel", chapter: 4, summary: "언약궤 빼앗김 — 홉니, 비느하스 전사, 엘리 죽음" },
  { book_id: "1samuel", chapter: 5, summary: "다곤 신전의 궤 — 다곤 상 엎어지고 블레셋에 재앙" },
  { book_id: "1samuel", chapter: 6, summary: "궤 반환 — 금 쥐와 독종 모형, 벧세메스로 돌아옴" },
  { book_id: "1samuel", chapter: 7, summary: "미스바 회개 — 사무엘의 중보, 에벤에셀의 돌" },
  { book_id: "1samuel", chapter: 8, summary: "왕을 달라는 백성 — 사무엘의 경고에도 왕정 요구" },
  { book_id: "1samuel", chapter: 9, summary: "사울의 등장 — 잃어버린 암나귀를 찾다가 사무엘을 만남" },
  { book_id: "1samuel", chapter: 10, summary: "사울의 기름부음 — 예언자 무리, 미스바에서 왕으로 추대" },
  { book_id: "1samuel", chapter: 11, summary: "야베스 길르앗 구출 — 사울의 첫 군사적 승리" },
  { book_id: "1samuel", chapter: 12, summary: "사무엘의 고별 연설 — 왕을 세운 것에 대한 경고와 권면" },
  { book_id: "1samuel", chapter: 13, summary: "사울의 월권 제사 — 블레셋 전쟁 중 사무엘 대신 번제를 드림" },
  { book_id: "1samuel", chapter: 14, summary: "요나단의 모험 — 두 사람이 블레셋 부대 격파, 꿀 사건" },
  { book_id: "1samuel", chapter: 15, summary: "아말렉 진멸 명령 불순종 — 사울의 왕위 폐함 선언" },
  { book_id: "1samuel", chapter: 16, summary: "다윗의 기름부음 — 이새의 막내아들, 사울의 악령과 수금" },
  { book_id: "1samuel", chapter: 17, summary: "다윗과 골리앗 — 물매돌 하나로 블레셋 거인 처치" },
  { book_id: "1samuel", chapter: 18, summary: "다윗과 요나단의 우정 — 사울의 시기, 미갈과의 결혼" },
  { book_id: "1samuel", chapter: 19, summary: "사울의 살해 시도 — 미갈의 도움, 다윗이 사무엘에게 도피" },
  { book_id: "1samuel", chapter: 20, summary: "요나단과의 작별 — 화살 신호로 사울의 살의를 확인" },
  { book_id: "1samuel", chapter: 21, summary: "다윗의 도피 — 놉의 제사장에게서 진설병과 골리앗의 칼" },
  { book_id: "1samuel", chapter: 22, summary: "아둘람 굴과 놉 학살 — 사울이 제사장 85명을 죽임" },
  { book_id: "1samuel", chapter: 23, summary: "그일라 구출과 십 광야 — 요나단의 마지막 방문" },
  { book_id: "1samuel", chapter: 24, summary: "엔게디 동굴 — 다윗이 사울의 옷자락을 벰, 복수하지 않음" },
  { book_id: "1samuel", chapter: 25, summary: "나발과 아비가일 — 어리석은 남편과 지혜로운 아내" },
  { book_id: "1samuel", chapter: 26, summary: "십 광야 재회 — 다윗이 자는 사울의 창과 물병을 가져감" },
  { book_id: "1samuel", chapter: 27, summary: "다윗의 블레셋 망명 — 아기스 왕에게 의탁, 시글락 거주" },
  { book_id: "1samuel", chapter: 28, summary: "엔돌의 신접한 여인 — 사울이 죽은 사무엘의 영을 불러냄" },
  { book_id: "1samuel", chapter: 29, summary: "다윗의 전쟁 면제 — 블레셋 방백들이 다윗을 돌려보냄" },
  { book_id: "1samuel", chapter: 30, summary: "시글락 탈환 — 아말렉에게 약탈당한 가족과 재산 회복" },
  { book_id: "1samuel", chapter: 31, summary: "길보아 산 전투 — 사울과 세 아들 전사, 비극적 최후" },

  // ── 사무엘하 (2 Samuel) 24장 ──
  { book_id: "2samuel", chapter: 1, summary: "사울의 죽음 소식 — 다윗의 애가, 활 노래" },
  { book_id: "2samuel", chapter: 2, summary: "다윗 유다 왕 즉위 — 이스보셋과의 분열, 기브온 연못 전투" },
  { book_id: "2samuel", chapter: 3, summary: "아브넬의 투항과 죽음 — 요압이 아브넬을 헤브론에서 암살" },
  { book_id: "2samuel", chapter: 4, summary: "이스보셋 암살 — 바아나와 레갑의 범행, 다윗의 처벌" },
  { book_id: "2samuel", chapter: 5, summary: "다윗 통일왕 즉위 — 예루살렘 정복, 블레셋 두 차례 격파" },
  { book_id: "2samuel", chapter: 6, summary: "궤를 예루살렘으로 — 웃사 사건, 다윗이 옷 벗고 춤춤" },
  { book_id: "2samuel", chapter: 7, summary: "다윗 언약 — 네 집과 나라가 영원히 견고하리라" },
  { book_id: "2samuel", chapter: 8, summary: "다윗의 정복 전쟁 — 모압, 소바, 에돔 격파" },
  { book_id: "2samuel", chapter: 9, summary: "므비보셋에 대한 은총 — 요나단의 아들을 왕의 식탁에 앉힘" },
  { book_id: "2samuel", chapter: 10, summary: "암몬과의 전쟁 — 사절 모욕 사건, 요압과 아비새의 승리" },
  { book_id: "2samuel", chapter: 11, summary: "다윗과 밧세바 — 간음과 우리아를 전쟁터에서 죽게 함" },
  { book_id: "2samuel", chapter: 12, summary: "나단의 책망 — 가난한 자의 어린 양 비유, 첫 아이 죽음, 솔로몬 탄생" },
  { book_id: "2samuel", chapter: 13, summary: "암논과 다말 — 이복누이 강간 사건, 압살롬의 복수 계획" },
  { book_id: "2samuel", chapter: 14, summary: "압살롬 귀환 — 요압의 계략, 2년간 왕의 얼굴을 보지 못함" },
  { book_id: "2samuel", chapter: 15, summary: "압살롬의 반역 — 헤브론에서 모반, 다윗의 예루살렘 탈출" },
  { book_id: "2samuel", chapter: 16, summary: "시므이의 저주 — 다윗에게 돌을 던짐, 아히도벨의 조언" },
  { book_id: "2samuel", chapter: 17, summary: "아히도벨 vs 후새 — 후새의 조언 채택, 아히도벨 자결" },
  { book_id: "2samuel", chapter: 18, summary: "압살롬의 죽음 — 상수리나무에 머리카락이 걸림, 요압이 죽임" },
  { book_id: "2samuel", chapter: 19, summary: "다윗의 귀환 — 요단강 도하, 시므이 용서, 므비보셋 변명" },
  { book_id: "2samuel", chapter: 20, summary: "세바의 반란 — 요압이 아마사를 죽이고 반란 진압" },
  { book_id: "2samuel", chapter: 21, summary: "기브온 사람들의 복수 — 사울의 후손 7명 처형, 리스바의 모정" },
  { book_id: "2samuel", chapter: 22, summary: "다윗의 감사 시 — 구원의 하나님을 찬양하는 노래" },
  { book_id: "2samuel", chapter: 23, summary: "다윗의 마지막 말씀 — 30용사와 37인 용사 명단" },
  { book_id: "2samuel", chapter: 24, summary: "인구조사 죄 — 전염병 재앙, 아라우나 타작마당 구입" },

  // ── 열왕기상 (1 Kings) 22장 ──
  { book_id: "1kings", chapter: 1, summary: "솔로몬 왕위 계승 — 아도니야의 찬탈 시도 저지" },
  { book_id: "1kings", chapter: 2, summary: "다윗의 유언과 죽음 — 솔로몬이 정적 제거로 왕권 확립" },
  { book_id: "1kings", chapter: 3, summary: "솔로몬의 지혜 — 두 창녀의 아이 재판, 하나님께 지혜를 구함" },
  { book_id: "1kings", chapter: 4, summary: "솔로몬의 번영 — 12지방관 체제, 잠언 3,000개, 노래 1,005편" },
  { book_id: "1kings", chapter: 5, summary: "성전 건축 준비 — 히람 왕과 백향목 교역 계약" },
  { book_id: "1kings", chapter: 6, summary: "성전 건축 — 7년간 건축, 지성소와 그룹 조각" },
  { book_id: "1kings", chapter: 7, summary: "솔로몬 궁전과 성전 기물 — 놋 기둥 야긴과 보아스" },
  { book_id: "1kings", chapter: 8, summary: "성전 봉헌식 — 솔로몬의 기도와 영광의 구름" },
  { book_id: "1kings", chapter: 9, summary: "하나님의 응답 — 솔로몬에 대한 축복과 경고" },
  { book_id: "1kings", chapter: 10, summary: "스바 여왕의 방문 — 솔로몬의 지혜와 부귀에 감탄" },
  { book_id: "1kings", chapter: 11, summary: "솔로몬의 타락 — 이방 여인들과 우상숭배, 왕국 분열 예고" },
  { book_id: "1kings", chapter: 12, summary: "왕국 분열 — 르호보암의 폭정, 여로보암이 북이스라엘 왕이 됨" },
  { book_id: "1kings", chapter: 13, summary: "하나님의 사람과 늙은 선지자 — 벧엘 제단 예언, 사자에게 죽임" },
  { book_id: "1kings", chapter: 14, summary: "여로보암과 르호보암의 악정 — 아히야의 심판 예언" },
  { book_id: "1kings", chapter: 15, summary: "남유다 아비얌·아사, 북이스라엘 나답·바아사 왕" },
  { book_id: "1kings", chapter: 16, summary: "북이스라엘 왕조 교체 — 엘라, 시므리, 오므리, 아합 즉위" },
  { book_id: "1kings", chapter: 17, summary: "엘리야의 등장 — 그릿 시냇가 까마귀, 사르밧 과부의 기적" },
  { book_id: "1kings", chapter: 18, summary: "갈멜 산 대결 — 바알 선지자 450명 대 엘리야, 불이 내림" },
  { book_id: "1kings", chapter: 19, summary: "호렙 산의 엘리야 — 세미한 소리, 엘리사 부름" },
  { book_id: "1kings", chapter: 20, summary: "아합의 아람 전쟁 — 두 차례 승리 후 벤하닷을 놓아줌" },
  { book_id: "1kings", chapter: 21, summary: "나봇의 포도원 — 이세벨의 모략으로 나봇 살해, 엘리야의 심판 선언" },
  { book_id: "1kings", chapter: 22, summary: "아합의 전사 — 미가야의 참된 예언, 라못 길르앗 전투에서 죽음" },

  // ── 열왕기하 (2 Kings) 25장 ──
  { book_id: "2kings", chapter: 1, summary: "아하시야의 죽음 — 바알세붑에게 묻다가 엘리야의 심판" },
  { book_id: "2kings", chapter: 2, summary: "엘리야 승천 — 불 병거와 회오리바람, 엘리사의 겉옷" },
  { book_id: "2kings", chapter: 3, summary: "모압 원정 — 엘리사의 도움으로 물 공급과 승리" },
  { book_id: "2kings", chapter: 4, summary: "엘리사의 기적들 — 기름 병, 수넴 여인의 아들 부활, 독 국 치료" },
  { book_id: "2kings", chapter: 5, summary: "나아만 장군의 문둥병 치유 — 요단강에 7번 몸을 씻음" },
  { book_id: "2kings", chapter: 6, summary: "도끼머리 물 위에 뜸 — 아람군 눈멀게 함, 사마리아 포위" },
  { book_id: "2kings", chapter: 7, summary: "사마리아 기근 해결 — 문둥병자 4명이 아람 진영 버려진 것 발견" },
  { book_id: "2kings", chapter: 8, summary: "수넴 여인 땅 회복 — 하사엘이 벤하닷 암살, 아람 왕 됨" },
  { book_id: "2kings", chapter: 9, summary: "예후의 기름부음 — 요람과 아하시야 죽임, 이세벨 처형" },
  { book_id: "2kings", chapter: 10, summary: "예후의 숙청 — 아합의 70아들 처형, 바알 숭배자 전멸" },
  { book_id: "2kings", chapter: 11, summary: "아달랴의 찬탈 — 요아스 6년간 숨김, 여호야다의 쿠데타" },
  { book_id: "2kings", chapter: 12, summary: "요아스의 성전 보수 — 헌금함 설치, 하사엘에게 조공" },
  { book_id: "2kings", chapter: 13, summary: "여호아하스와 요아스 — 엘리사의 죽음과 뼈에 닿아 부활" },
  { book_id: "2kings", chapter: 14, summary: "아마샤와 여로보암 2세 — 남북 전쟁, 북이스라엘의 영토 회복" },
  { book_id: "2kings", chapter: 15, summary: "아사랴(웃시야)와 북이스라엘 말기 왕들 — 왕위 찬탈 연속" },
  { book_id: "2kings", chapter: 16, summary: "아하스의 우상숭배 — 앗수르에 의탁, 다메섹 제단 모방" },
  { book_id: "2kings", chapter: 17, summary: "북이스라엘 멸망 — 앗수르 살만에셀에게 함락, 사마리아 혼합 민족" },
  { book_id: "2kings", chapter: 18, summary: "히스기야의 개혁 — 앗수르 산헤립의 예루살렘 위협" },
  { book_id: "2kings", chapter: 19, summary: "이사야의 예언 — 여호와의 사자가 앗수르 185,000명을 침" },
  { book_id: "2kings", chapter: 20, summary: "히스기야의 병과 치유 — 해시계 10도 뒤로, 15년 수명 연장" },
  { book_id: "2kings", chapter: 21, summary: "므낫세의 극심한 우상숭배 — 55년간 악정, 아몬 왕" },
  { book_id: "2kings", chapter: 22, summary: "요시야의 율법책 발견 — 성전 수리 중 발견, 훌다의 예언" },
  { book_id: "2kings", chapter: 23, summary: "요시야의 종교 개혁 — 산당 파괴, 유월절 회복" },
  { book_id: "2kings", chapter: 24, summary: "바벨론의 1·2차 침공 — 여호야긴 포로, 시드기야 옹립" },
  { book_id: "2kings", chapter: 25, summary: "예루살렘 함락과 성전 파괴 — 바벨론 포로, 그달리야 암살" },

  // ── 역대상 (1 Chronicles) 29장 ──
  { book_id: "1chronicles", chapter: 1, summary: "아담부터 에서까지 족보 — 인류와 이스라엘의 계보" },
  { book_id: "1chronicles", chapter: 2, summary: "유다 지파 족보 — 야곱의 아들들부터 다윗의 가문까지" },
  { book_id: "1chronicles", chapter: 3, summary: "다윗의 아들들과 유다 왕 족보 — 솔로몬부터 포로기까지" },
  { book_id: "1chronicles", chapter: 4, summary: "유다·시므온 지파 족보 — 야베스의 기도" },
  { book_id: "1chronicles", chapter: 5, summary: "르우벤·갓·므낫세 반 지파 — 요단 동편 지파 족보" },
  { book_id: "1chronicles", chapter: 6, summary: "레위 지파 족보 — 제사장 가문과 성가대, 레위 성읍" },
  { book_id: "1chronicles", chapter: 7, summary: "잇사갈·베냐민·납달리·므낫세·에브라임·아셀 족보" },
  { book_id: "1chronicles", chapter: 8, summary: "베냐민 지파 상세 족보 — 사울 왕의 가계" },
  { book_id: "1chronicles", chapter: 9, summary: "예루살렘 귀환자 명단 — 성전 문지기와 봉사자" },
  { book_id: "1chronicles", chapter: 10, summary: "사울의 죽음 — 길보아 전투 패배, 비참한 최후" },
  { book_id: "1chronicles", chapter: 11, summary: "다윗 통일왕 즉위 — 예루살렘 정복, 용사 명단" },
  { book_id: "1chronicles", chapter: 12, summary: "다윗에게 합류한 용사들 — 각 지파에서 온 전사들" },
  { book_id: "1chronicles", chapter: 13, summary: "궤 운반 시도 — 웃사가 궤에 손을 대고 죽음" },
  { book_id: "1chronicles", chapter: 14, summary: "히람의 궁전 건축 지원 — 블레셋 두 차례 격파" },
  { book_id: "1chronicles", chapter: 15, summary: "궤를 예루살렘으로 — 레위인이 메고, 다윗이 춤추며 행진" },
  { book_id: "1chronicles", chapter: 16, summary: "궤 봉안과 찬양 — 다윗의 감사 시편, 아삽의 봉사" },
  { book_id: "1chronicles", chapter: 17, summary: "다윗 언약 — 나단을 통해 영원한 왕조를 약속하심" },
  { book_id: "1chronicles", chapter: 18, summary: "다윗의 정복 전쟁 — 블레셋, 모압, 소바, 에돔 정복" },
  { book_id: "1chronicles", chapter: 19, summary: "암몬과 아람 전쟁 — 사절 모욕, 요압의 승리" },
  { book_id: "1chronicles", chapter: 20, summary: "랍바 정복과 블레셋 거인들 처치" },
  { book_id: "1chronicles", chapter: 21, summary: "다윗의 인구조사 — 전염병, 오르난 타작마당 매입" },
  { book_id: "1chronicles", chapter: 22, summary: "성전 건축 준비 — 다윗이 솔로몬에게 자재와 유훈을 남김" },
  { book_id: "1chronicles", chapter: 23, summary: "레위인 조직 편성 — 30세 이상 38,000명 직무 배정" },
  { book_id: "1chronicles", chapter: 24, summary: "제사장 24반열 편성 — 아론 자손의 직무 분담" },
  { book_id: "1chronicles", chapter: 25, summary: "성가대 24반열 — 아삽, 헤만, 여두둔 자손의 음악 봉사" },
  { book_id: "1chronicles", chapter: 26, summary: "문지기와 창고지기 편성 — 성전 수비와 재정 관리" },
  { book_id: "1chronicles", chapter: 27, summary: "군사·행정 조직 — 12달 반장과 지파 지도자, 왕실 관리" },
  { book_id: "1chronicles", chapter: 28, summary: "다윗의 유언 — 솔로몬에게 성전 설계도와 건축 명령" },
  { book_id: "1chronicles", chapter: 29, summary: "성전 헌금과 다윗의 마지막 기도 — 솔로몬 즉위" },

  // ── 역대하 (2 Chronicles) 36장 ──
  { book_id: "2chronicles", chapter: 1, summary: "솔로몬의 지혜 구함 — 기브온 제사, 하나님의 응답" },
  { book_id: "2chronicles", chapter: 2, summary: "성전 건축 준비 — 두로 왕 후람과 자재·인력 계약" },
  { book_id: "2chronicles", chapter: 3, summary: "성전 건축 시작 — 모리아 산, 지성소와 두 그룹" },
  { book_id: "2chronicles", chapter: 4, summary: "성전 기물 제작 — 놋 바다, 등잔대, 금 제단" },
  { book_id: "2chronicles", chapter: 5, summary: "궤를 성전에 안치 — 영광의 구름이 성전에 가득 참" },
  { book_id: "2chronicles", chapter: 6, summary: "솔로몬의 봉헌 기도 — 하늘에서 들으시고 용서하소서" },
  { book_id: "2chronicles", chapter: 7, summary: "하늘에서 불이 내림 — 내 이름으로 기도하면 땅을 고치리라" },
  { book_id: "2chronicles", chapter: 8, summary: "솔로몬의 건축과 행정 — 성읍 건설, 제사 규례 확립" },
  { book_id: "2chronicles", chapter: 9, summary: "스바 여왕의 방문 — 솔로몬의 지혜와 부귀, 솔로몬 죽음" },
  { book_id: "2chronicles", chapter: 10, summary: "왕국 분열 — 르호보암의 가혹한 답변, 10지파 이탈" },
  { book_id: "2chronicles", chapter: 11, summary: "르호보암의 방비 — 레위인과 경건한 자들이 남유다로 이주" },
  { book_id: "2chronicles", chapter: 12, summary: "시삭의 침공 — 르호보암의 배반, 성전 보물 약탈" },
  { book_id: "2chronicles", chapter: 13, summary: "아비야의 승리 — 여로보암의 80만 대군을 40만으로 격파" },
  { book_id: "2chronicles", chapter: 14, summary: "아사의 개혁과 승리 — 에티오피아 세라의 100만 대군 격파" },
  { book_id: "2chronicles", chapter: 15, summary: "아사리야의 예언 — 아사의 종교 개혁과 언약 갱신" },
  { book_id: "2chronicles", chapter: 16, summary: "아사의 말년 실패 — 아람에 의지, 하나니 선지자 투옥" },
  { book_id: "2chronicles", chapter: 17, summary: "여호사밧의 개혁 — 율법 교육 파견, 국력 강화" },
  { book_id: "2chronicles", chapter: 18, summary: "아합과의 동맹 — 미가야의 경고, 라못 길르앗 전투" },
  { book_id: "2chronicles", chapter: 19, summary: "여호사밧의 사법 개혁 — 재판관 임명, 공의 촉구" },
  { book_id: "2chronicles", chapter: 20, summary: "모압·암몬 연합군 격퇴 — 찬양대를 앞세워 승리" },
  { book_id: "2chronicles", chapter: 21, summary: "여호람의 악정 — 형제 살해, 에돔 반란, 엘리야의 편지" },
  { book_id: "2chronicles", chapter: 22, summary: "아하시야와 아달랴 — 예후에게 죽임, 아달랴의 찬탈" },
  { book_id: "2chronicles", chapter: 23, summary: "여호야다의 거사 — 요아스 즉위, 아달랴 처형" },
  { book_id: "2chronicles", chapter: 24, summary: "요아스의 성전 보수 — 여호야다 사후 타락, 스가랴 살해" },
  { book_id: "2chronicles", chapter: 25, summary: "아마샤의 에돔 승리와 교만 — 북이스라엘에 패배" },
  { book_id: "2chronicles", chapter: 26, summary: "웃시야의 번영과 교만 — 분향 월권, 문둥병에 걸림" },
  { book_id: "2chronicles", chapter: 27, summary: "요담의 선정 — 성전 윗문 건축, 암몬 정복" },
  { book_id: "2chronicles", chapter: 28, summary: "아하스의 극심한 우상숭배 — 아람과 이스라엘에 패배" },
  { book_id: "2chronicles", chapter: 29, summary: "히스기야의 성전 정화 — 레위인 성별, 제사 회복" },
  { book_id: "2chronicles", chapter: 30, summary: "히스기야의 유월절 — 남북 통합 초청, 대규모 축제" },
  { book_id: "2chronicles", chapter: 31, summary: "십일조와 봉헌물 — 산당 파괴, 제사장·레위인 지원 체계" },
  { book_id: "2chronicles", chapter: 32, summary: "산헤립의 침공 — 히스기야의 기도, 185,000명 멸절" },
  { book_id: "2chronicles", chapter: 33, summary: "므낫세의 회개 — 포로 중 기도, 돌아와 개혁" },
  { book_id: "2chronicles", chapter: 34, summary: "요시야의 개혁 — 율법책 발견, 언약 갱신" },
  { book_id: "2chronicles", chapter: 35, summary: "요시야의 유월절 — 대규모 축제, 므깃도 전투에서 전사" },
  { book_id: "2chronicles", chapter: 36, summary: "유다의 마지막 왕들과 멸망 — 바벨론 포로, 고레스 칙령" },

  // ── 에스라 (Ezra) 10장 ──
  { book_id: "ezra", chapter: 1, summary: "고레스의 귀환 칙령 — 성전 기물 반환, 1차 귀환" },
  { book_id: "ezra", chapter: 2, summary: "귀환자 명단 — 42,360명과 종 7,337명" },
  { book_id: "ezra", chapter: 3, summary: "제단 재건과 성전 기초 — 기초 놓을 때 울며 기뻐함" },
  { book_id: "ezra", chapter: 4, summary: "성전 건축 방해 — 대적의 고소로 공사 중단" },
  { book_id: "ezra", chapter: 5, summary: "학개·스가랴의 권면 — 성전 재건 재개, 다리오에게 보고" },
  { book_id: "ezra", chapter: 6, summary: "다리오의 허가와 성전 완공 — 유월절 거행" },
  { book_id: "ezra", chapter: 7, summary: "에스라의 2차 귀환 — 아닥사스다의 조서, 율법 교사" },
  { book_id: "ezra", chapter: 8, summary: "귀환 동행자 명단 — 아하와 강가 금식, 안전한 여정" },
  { book_id: "ezra", chapter: 9, summary: "이방인과의 통혼 문제 — 에스라의 통곡과 참회 기도" },
  { book_id: "ezra", chapter: 10, summary: "이방 아내 보냄 — 세가냐의 제안, 혼인 청산 실행" },

  // ── 느헤미야 (Nehemiah) 13장 ──
  { book_id: "nehemiah", chapter: 1, summary: "느헤미야의 기도 — 예루살렘 성벽 무너진 소식에 통곡" },
  { book_id: "nehemiah", chapter: 2, summary: "아닥사스다 왕의 허가 — 예루살렘 성벽 야간 답사" },
  { book_id: "nehemiah", chapter: 3, summary: "성벽 재건 구역 배정 — 각 가문별 담당 구역 기록" },
  { book_id: "nehemiah", chapter: 4, summary: "산발랏·도비야의 방해 — 한 손에 무기, 한 손에 연장" },
  { book_id: "nehemiah", chapter: 5, summary: "가난한 백성 구제 — 느헤미야가 고리대금 폐지 촉구" },
  { book_id: "nehemiah", chapter: 6, summary: "성벽 52일 만에 완공 — 산발랏의 음모 5차례 좌절" },
  { book_id: "nehemiah", chapter: 7, summary: "성문 경비 배치와 귀환자 족보 확인" },
  { book_id: "nehemiah", chapter: 8, summary: "에스라의 율법 낭독 — 수문 앞 광장, 백성이 울며 들음" },
  { book_id: "nehemiah", chapter: 9, summary: "백성의 참회 기도 — 이스라엘 역사를 회고하며 회개" },
  { book_id: "nehemiah", chapter: 10, summary: "언약 갱신 서명 — 안식일·십일조·성전 봉사 서약" },
  { book_id: "nehemiah", chapter: 11, summary: "예루살렘 거주자 배정 — 제비뽑아 10분의 1 이주" },
  { book_id: "nehemiah", chapter: 12, summary: "성벽 봉헌식 — 두 감사 행렬, 레위인 찬양대" },
  { book_id: "nehemiah", chapter: 13, summary: "느헤미야의 2차 개혁 — 안식일·십일조·통혼 문제 시정" },

  // ── 에스더 (Esther) 10장 ──
  { book_id: "esther", chapter: 1, summary: "왕후 와스디 폐위 — 아하수에로 왕의 잔치, 명령 거부" },
  { book_id: "esther", chapter: 2, summary: "에스더 왕후 간택 — 모르드개의 양녀, 왕의 총애를 받음" },
  { book_id: "esther", chapter: 3, summary: "하만의 유다인 학살 칙령 — 모르드개 불경에 분노" },
  { book_id: "esther", chapter: 4, summary: "모르드개의 촉구 — 이때를 위함이 아닌지 누가 알겠느냐" },
  { book_id: "esther", chapter: 5, summary: "에스더의 첫째 잔치 — 하만이 모르드개 교수대 준비" },
  { book_id: "esther", chapter: 6, summary: "모르드개 존귀 — 왕의 불면, 하만이 모르드개를 태워 행진" },
  { book_id: "esther", chapter: 7, summary: "하만의 몰락 — 에스더의 고발, 하만이 자기 교수대에 매달림" },
  { book_id: "esther", chapter: 8, summary: "유다인의 자위권 칙령 — 모르드개의 새 조서 반포" },
  { book_id: "esther", chapter: 9, summary: "부림절 제정 — 유다인의 승리, 아달 14-15일 기념" },
  { book_id: "esther", chapter: 10, summary: "모르드개의 영광 — 왕 다음가는 지위에 오름" },
];

async function insertChapters() {
  console.log(`Starting insertion of ${chapters.length} chapter summaries...\n`);

  const sql = `INSERT INTO book_chapters (book_id, chapter, summary) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE summary=VALUES(summary)`;

  let count = 0;
  let currentBook = "";

  for (const ch of chapters) {
    if (ch.book_id !== currentBook) {
      if (currentBook) {
        console.log(`  Done: ${currentBook}\n`);
      }
      currentBook = ch.book_id;
      console.log(`Inserting ${currentBook}...`);
    }

    await db.execute(sql, [ch.book_id, ch.chapter, ch.summary]);
    count++;
  }

  console.log(`  Done: ${currentBook}\n`);
  console.log(`\nCompleted: ${count} chapter summaries inserted successfully.`);
}

insertChapters().catch((err) => {
  console.error("Error:", err);
  process.exit(1);
});
